name: First Workflow

on:
    workflow_dispatch:

jobs:
    example-job:
      runs-on: ubuntu-latest
      steps:
      - name: Run a simple command
        run: echo "Hello, world!"
      - name: Cowsays
        # You may pin to the exact commit or the version.
        # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: Ship it!!!!!
          # Color of your cow
          color: green
           
